### ISSUE TITLE
Pulsemeeter started and running no GUI/errors

### ISSUE THREAD

**Issue by ZerkerEOD** [theRealCarneiro/pulsemeeter#69] opened 2022-07-22 13:34 UTC
**Describe the bug**
Pulsemeeter GUI does not appear, not located in the systray and if I try to open the application I see a pulsemeeter icon show as a blank document and it says its a text editor. Unable to find any GUI, and the terminal will say its already running which is verified when looking at my audio outputs as I have virtual ones appear.

**To Reproduce**
1. Type `pulsemeeter daemon` or `pulsemeeter init`

**Expected behavior**
Pulsemeeter GUI appears

**Screenshots**
![image](https://user-images.githubusercontent.com/26573385/180449352-a90ee816-6b14-4efb-91f0-db2dc084eb42.png)
![image](https://user-images.githubusercontent.com/26573385/180449427-f002c40b-bc99-4bdd-888f-6b14cd5a2ba7.png)
![image](https://user-images.githubusercontent.com/26573385/180449552-44f6f803-1760-4712-a83f-1409b9b34f8c.png)
![image](https://user-images.githubusercontent.com/26573385/180449611-b32a7947-4540-4496-ab6e-78485994b8cb.png)
![image](https://user-images.githubusercontent.com/26573385/180450152-22291eb8-d1b6-48b0-bd37-4ddd948def58.png)

**Desktop (please complete the following information):**
 - Distro: Linux-5.18.0-kali2-amd64-x86_64-with-glibc2.33
 - Python Version: 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0]
 - Desktop ENV: KDE plasmashell 5.24.5

**Additional context**
Nothing additional for now.

**Comment by ZerkerEOD** [comment] 2022-07-22 13:47
I finally managed to get an error better error message pop up.

```
pulsemeeter daemon
ERROR: invalid json 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pulsemeeter/interface/main_window.py", line 728, in open_ui
    self.windowinstance = self.start_window(self.isserver)
  File "/usr/local/lib/python3.10/dist-packages/pulsemeeter/interface/main_window.py", line 103, in start_window
    self.devices['hi'] = self.client.list_hardware_devices('sources')
  File "/usr/local/lib/python3.10/dist-packages/pulsemeeter/socket/client.py", line 395, in list_hardware_devices
    return json.loads(self.send_command(f'get-hd {device_type}'))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Fl1tzi** [comment] 2022-07-22 14:25
Hi.

`pulsemeeter daemon` just starts the server and not the gui. 

The other problem is a duplicate of #65.

**Closed** 2022-07-22 14:26 UTC
Labels: duplicate

**Comment by ZerkerEOD** [comment] 2022-07-22 14:28
@Fl1tzi, I saw that one but the error message looks similar but different. Looks like mine is having trouble decoding the json and not able to open the UI.

**Comment by Fl1tzi** [comment] 2022-07-22 14:36
@ZerkerEOD both have the same traceback and are just started different. But they are basically just the same error.
